### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by graeme-a-stewart** [HSF/hsf.github.io#1043]
As there's been a lot of discussion in many communities about the conotations of git's default `master` branch (which I don't want to repeat here), but I'd like to propose that we rename the development branch of `hsf.github.io` to `main` which is a very acceptable alternative.

It's rather easy to do, following instructions like this: <https://github.com/github/renaming>.

**Comment by klieret** [comment]
Any update @graeme-a-stewart ?

**Comment by klieret** [comment]
Pushing for a this, just because all of my muscle-memory meanwhile does `checkout main` ;)

**Comment by hegner** [comment]
@graeme-a-stewart - will bring that up in the next coordination meeting, And then just execute...

**Comment by adi-develops** [comment]
Hi! Please assign this issue to me. I can rename the master branch to main. I also think it would be more convenient.
