### ISSUE TITLE
Broken link for Training roles on the Training Working Group page

### ISSUE THREAD

**Issue by amangoel185** [HSF/hsf.github.io#1124]
The link for _Training roles_ is broken on the website.

If it's intended to point to [Educators](https://hepsoftwarefoundation.org/training/educators.html), [#L138](https://github.com/HSF/hsf.github.io/blob/057028d0d8b6d5baaaee44f5e77e03866e73dd71/_workinggroups/training.md?plain=1#L138) in [hsf.github.io/_workinggroups/training.md](https://github.com/HSF/hsf.github.io/blob/057028d0d8b6d5baaaee44f5e77e03866e73dd71/_workinggroups/training.md) can be fixed by changing `<a href="h/training/educators.html">` to `<a href="educators.html">`.

**Comment by klieret** [comment]
Thanks @amangoel185  I've opened a PR for this
