### ISSUE TITLE
HSF website should have updated events

### ISSUE THREAD

**Issue by wdconinc** [HSF/hsf.github.io#1161]
The HSF front page still lists April and May events:
![image](https://user-images.githubusercontent.com/4656391/178493028-be725eec-0717-4c3d-8bd8-5da221e60dcf.png)

Should this be updated automatically? There have been website builds since then which should have picked up more recent ical events.

@graeme-a-stewart

**Comment by hegner** [comment]
Hi @wdconinc - I did not add the last minutes. Once I did that I will check whether it hangs somewhere.

**Comment by hegner** [comment]
It seems we are back to fine again here. I will close the ticket

What remains is to put the GSoC blogs on the frontpage, but that's a different issue
