### ISSUE TITLE
Machine learning is mentioned twice on the curriculum page

### ISSUE THREAD

**Issue by amanmdesai** [HSF/hsf.github.io#1216]
Machine Learning is mentioned twice on the curriculum page, once in the Basics section and then in Machine Learning Section.

Curriculum page:
https://hepsoftwarefoundation.org/training/curriculum.html

**Comment by amanmdesai** [comment]
@klieret

**Comment by klieret** [comment]
Hi @amanmdesai . Thanks for taking a critical look at the curriculum. 

IIRC this was intended though (with the logic that ML is pretty much "Basic knowledge" meanwhile)
