### ISSUE TITLE
Create .github repository in organization

### ISSUE THREAD

**Issue by klieret** [HSF/hsf.github.io#1244]
Creating this issue here for lack of better alternatives: Organizations can have a "global" readme. Like this for hsf-training:

![image](https://user-images.githubusercontent.com/13602468/189718858-fc02643b-b1fc-4e8a-be3c-6abe85cf26eb.png)

Specifically I'd really like it if we could add a clearly visible link to the hsf-training github organization.

**Comment by klieret** [comment]
I'd vote on just creating a blank one and then we can review PRs there

**Comment by graeme-a-stewart** [comment]
I see - I was wondering how this could be achived, because it would be nice to use the GH org itself as entry point. It seems also very useful for sharing resources between the more specific repositories.

**Comment by graeme-a-stewart** [comment]
Done: <https://github.com/HSF/.github>
