### ISSUE TITLE
Fix mobile layout of floating pictures

### ISSUE THREAD

**Issue by klieret** [HSF/hsf.github.io#1247]
* **Required knowledge**: HTML, CSS

The floating pictures on https://hepsoftwarefoundation.org/workinggroups/training.html get very very small on a mobile layout. Instead they should just flow to "interrupt" the text.

**Comment by developer-irfan** [comment]
Hello @klieret, yes pictures get very small on mobile device bcz they are not responsive and are in the same row of text. just assign me this i will solve this so in order the pics are display properly. thankyou

**Comment by klieret** [comment]
Thank you for your interest @developer-irfan !  There was already one PR (#1250) about this, but unfortunately I do not think that it does what we need. I'd be quite happy if you'd give it a try as well or leave a comment at #1250 :)

**Comment by Ahnaf-codes** [comment]
is this good? @klieret 
![Screenshot 2022-10-06 at 22-40-55 HSF Training](https://user-images.githubusercontent.com/102795582/194370370-3dbe568a-406a-435f-87bb-4c59801a5bfc.png)

**Comment by klieret** [comment]
Thanks for taking a look at that :) Already much better! But could we in principle also have it simply take 100% of the width if we are at such small display sizes?

**Comment by Ahnaf-codes** [comment]
yeah thats pretty simple. ill send a pic

**Comment by Ahnaf-codes** [comment]
![Screenshot 2022-10-06 at 22-56-24 HSF Training](https://user-images.githubusercontent.com/102795582/194373328-5c292bef-1814-49cc-a397-650454644a6f.png)
@klieret

**Comment by klieret** [comment]
That looks perfect! :D

**Comment by Ahnaf-codes** [comment]
ill send the pr tomorrow since im kinda tired

**Comment by Ahnaf-codes** [comment]
@klieret its done
