### ISSUE TITLE
Jekyll: Fix superfluous closing div in list of educators per year

### ISSUE THREAD

**Issue by klieret** [HSF/hsf.github.io#1260]
**Required knowledge:** Jekyll, liquid

The logic that needs to be fixed is at https://github.com/HSF/hsf.github.io/blob/master/_includes/list_of_educators.html

If a new year starts and now educator has been registered for that year, a superfluous `</div>` is printed (see also comment at the bottom of the page)

**Comment by himanshu007-creator** [comment]
Hi @klieret , i would like to work on this issue, can you help me understand what needs to be done?

**Comment by Bikisome** [comment]
hello @klieret sir i am a begginer in this open source community .i would like to contribute to this issu can you please help me about this .

**Comment by satyamsaxena2001** [comment]
![Screenshot from 2023-01-20 22-16-58](https://user-images.githubusercontent.com/95117179/213755723-92614aa4-9dcd-493e-965e-9701b40a7bf4.png)

@klieret is this the right way to do it. I would like to work on this if you can assign me the issue.

**Comment by klieret** [comment]
@satyamsaxena2001 Looks good! Feel free to create a PR with this solution!

**Comment by satyamsaxena2001** [comment]
@klieret i have created a PR.Please have a look and let me know.

**Comment by Chiranjeev-Kartik** [comment]
@klieret  Since the issue is still open, I would like to work on it.

**Comment by Xiexus26** [comment]
I would like to work on this issue since it is still open.
