### ISSUE TITLE
List of training schools: Only show "Current/upcoming" if there are any

### ISSUE THREAD

**Issue by klieret** [HSF/hsf.github.io#1298]
https://hepsoftwarefoundation.org/Schools/events.html: The current/upcoming section is shown even without corresponding events

**Comment by rohini-ranjanR** [comment]
We can achieve this by using the conditions https://discourse.gohugo.io/t/conditionally-include-some-text-in-markdown-file/30163 this may help.

**Comment by Azhar1327** [comment]
May i work on this ?

**Comment by klieret** [comment]
sure

**Comment by Bikisome** [comment]
can i work on this ?

**Comment by Bikisome** [comment]
hello @klieret sir i am a begginer i would like to contribute on your project ,can you please suggest how i should start

**Comment by Chiranjeev-Kartik** [comment]
@klieret  Since the issue is still open, I would like to work on it.

**Comment by Sulochan-khadka** [comment]
kindly assign me this issue to solve and specify the problem and the expected result.
