### ISSUE TITLE
Inconsistent navbar in low resolution

### ISSUE THREAD

**Issue by kartikaysaxena** [HSF/hsf.github.io#1391]
Navbar not consistent, text extends way beyond it as shown below
![IMG_4055](https://user-images.githubusercontent.com/120778728/223311830-8e6c60ca-9840-461a-969f-8791e634503b.PNG)

**Comment by thakurprathya** [comment]
That's a simple CSS Overflow issue, and same issue can be also be seen on other pages too like https://hepsoftwarefoundation.org/activities/gsoc.html
If no one is working on it, can I work on this issue.

**Comment by kartikaysaxena** [comment]
I have worked upon it, you can check other issues. Thanks.

**Comment by klieret** [comment]
Hi @kartikaysaxena , @thakurprathya . Thank you for raising this issue. Feel free to open a PR if there is an easy fix for this.

**Comment by eduardo-rodrigues** [comment]
Closing at this point since none of you picked the issue up and we site will be reworked.
