### ISSUE TITLE
Displaying dropdown on hover

### ISSUE THREAD

**Issue by gunjjoshi** [HSF/hsf.github.io#1471]
Currently, the sub-options in the navbar options appear in the dropdown only when they are clicked. To improve user friendliness, they must be visible as soon as the cursor hovers on them.

<img width="1470" alt="Screenshot 2023-12-13 at 10 15 04 PM" src="https://github.com/HSF/hsf.github.io/assets/67432819/f0d285a4-98bf-49e1-87dd-564ea2214b0b">

**Comment by Ansh-Sarkar** [comment]
Along with #1472 can take this up as well. Would allow me to get a comprehensive understanding of the entire code for enabling more valuable future contributions. Thanks!

**Comment by shivamkapoor172002** [comment]
i would love to contribute in this issue! can i ?

**Comment by Yashsharma009** [comment]
can i contribute to this issue. i am familiar with it as i have solved it.
