### ISSUE TITLE
Insufficient bottom margin 

### ISSUE THREAD

**Issue by gunjjoshi** [HSF/hsf.github.io#1472]
There is very little bottom margin for the line in footer, which is present in every page, except the homepage. It must be increased a bit.

<img width="1470" alt="Screenshot 2023-12-13 at 10 18 56 PM" src="https://github.com/HSF/hsf.github.io/assets/67432819/2dc9089b-1dd8-42a6-8461-091c64397226">

**Comment by Ansh-Sarkar** [comment]
Would love to work on this. Do let me know if the issue can be assigned to me. Thanks!

**Comment by Yashsharma009** [comment]
can i work on this issue ? i would love to work.

**Comment by klieret** [comment]
@gunjjoshi Thanks for the issue. It's generally best practice to leave the issue open until a fix has been merged (rather than just opened). You can even do [this automatically](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
