### ISSUE TITLE
URL checking is unreliable

### ISSUE THREAD

**Issue by graeme-a-stewart** [HSF/hsf.github.io#184]
As discussed in https://github.com/HEP-SF/hep-sf.github.io/pull/183 with @hegner and @jouvin , we now have so many external URLs in the HSF website we observe a significant failure rate from

- Websites that are really in downtime for some ~hours
- Temporary timeouts

Immediate retries would help with the later. A nightly check might help with the former.

However, we should be aware that over complicating the infrastructure for doing this would not be a good solution.

**Comment by hegner** [comment]
We should implement a check that only looks at URLs in the respective pull-request. To ensure long-term stability, I would suggest a weekly (not nightly) test. EP/SFT can provide it for the time being.

**Comment by jouvin** [comment]
It is not so easy to find the URLs changed in the pull request, this will  require a lot of parsing and I am not convinced that this is a good idea. As said somewhere else, I'd start by redoing the check (in the script used) in case of a failure. My experience with failing tests in our web site is that rerunning the test has always resulted in a successful test, except when there was really a problem. Trying this approach for a few weeks should be enough to see if it is an improvement or not.

**Comment by graeme-a-stewart** [comment]
@JavierCVilla just pointed out this alternative link checker:

<https://github.com/endymion/link-checker>

Might be worth looking at.
