### ISSUE TITLE
GSoC: improve multiple year support

### ISSUE THREAD

**Issue by jouvin** [HSF/hsf.github.io#240]
In 2018, support for multiple GSoC years has been added to proposal management. It is based on  a subdirectory per year in every GSoC-related collection/directory. One of the drawback is that year selection when building the proposal list per project or per organization is based on this directory structure, meaning that organizations and projects have to be redefined every year. In particular for organizations, this doesn't really make sense and result in file/information duplication. Suggested improvements are:

- [ ] support for organizations and projects that are not specific to one year. This requires a way to select the year we are interested to when asking the proposal related to a project/organization.
- [ ] Allow to list a multi-year list of proposals per project or organization, grouped by year

One possibility could be to create a project or organization page with all the projects for every year organized by section (year) with an anchor name which is the year and to add this anchor to the URL associated with the list of proposals in the main page so that the project/organization page is open directly at the relevant section.

**Comment by graeme-a-stewart** [comment]
Can we close this one now? It seems we have a working solution.

**Comment by xvallspl** [comment]
If no one complained this year I would suggest to close it already. Tagging @agheata
