### ISSUE TITLE
Redirects use absolute URLs

### ISSUE THREAD

**Issue by graeme-a-stewart** [HSF/hsf.github.io#310]
I noticed when adding a new redirect that there is an 'automatic' failure in the htmlproofer, because the redirect points to the absolute URL on `http://hepsoftwarefoundation.org`. Evidently this doesn't work as the PR has not yet been merged.

It may be possible to get [`jekyll-redirect-from`](https://github.com/jekyll/jekyll-redirect-from) to behave better (not clear from the docs how) or to use a different redirect plugin.

**Comment by jouvin** [comment]
Is not it enough to use the relative URL, in this case `/`?

**Comment by graeme-a-stewart** [comment]
AFAICR the redirector always uses the website address itself, so it becomes an absolute URL. We could play around a bit though...

**Comment by eduardo-rodrigues** [comment]
I believe this is sorted out at present?

**Comment by graeme-a-stewart** [comment]
Not as far as I know...

**Comment by graeme-a-stewart** [comment]
Well, it seems that we can live with this, if it still happens, so closing this old issue.
