### ISSUE TITLE
Rename hep-sf.github.io into hsf.github.io

### ISSUE THREAD

**Issue by jouvin** [HSF/hsf.github.io#324]
Needs to be done after the renaming of the organization as the repo name must match the organization name. We also need to:
* [ ] Update `hepsoftwarefoundation.org` CNAME (owned/managed by Torre)
* [x] Update the `CNAME` file in the repo
* [x] Rename repo to hsf.github.io

Follow-up for #323

**Comment by graeme-a-stewart** [comment]
OK, so shall I rename the repo now?

**Comment by jouvin** [comment]
In fact no need to update the `CNAME` file as the web site is still referred by the same domain. So yes, I suggest to rename the repo. I don't think it will impact the web site anyway until the CNAME is updated. @wenaus could you also update the CNAME now (it may take the DNS TTL to be visible...)

**Comment by graeme-a-stewart** [comment]
* [x] Rename repo to `hsf.github.io` (done)

**Comment by wenaus** [comment]
hsf.github.io still 404 for me. You want me to update the CNAME now anyway?

**Comment by graeme-a-stewart** [comment]
Fetching still seems to work - the old repo name is being redirected (thanks GitHub! 👍 )

**Comment by jouvin** [comment]
@wenaus Yes... this is also true for `hep-sf.github.io` due to the CNAME file in the repo saying that the domain associated with this repo is `hepsoftwarefoundation.org`.

@graeme-a-stewart I  saw the same thing for me!

**Comment by jouvin** [comment]
BTW, http://hepsoftwarefoundation.org still works... despite the contents has not been updated with the last PR mods. This is probably the most important.

**Comment by wenaus** [comment]
ok done, 5min ttl

**Comment by graeme-a-stewart** [comment]
@jouvin - I am seeing the last PR changes at http://hepsoftwarefoundation.org/ now. So at least my DNS seems to be updated.

Thanks @wenaus !

**Comment by jouvin** [comment]
Great!
