### ISSUE TITLE
Link to the old website in the description

### ISSUE THREAD

**Issue by JavierCVilla** [HSF/hsf.github.io#331]
Description of this repo still contains a reference to the old website name.

**Comment by graeme-a-stewart** [comment]
Hi @JavierCVilla - I am not seeing it, where exactly do you find it?

**Comment by JavierCVilla** [comment]
Hi @graeme-a-stewart ,

Following this [link](https://github.com/HSF/hsf.github.io) you get it:

![hep-sf-name](https://user-images.githubusercontent.com/4431174/37760753-de34b46e-2db7-11e8-8e5f-b4e34ba0a226.png)

**Comment by graeme-a-stewart** [comment]
Ah, yes, I missed that. OK, fixed now.

Thanks
