### ISSUE TITLE
Navigation between meetings

### ISSUE THREAD

**Issue by graeme-a-stewart** [HSF/hsf.github.io#332]
It would be nice to have "next meeting" "previous meeting" links on the minutes, as navigating through them is right now a bit of a pain.

**Comment by graeme-a-stewart** [comment]
This is useful for fixing this:

https://stackoverflow.com/questions/16145061/get-next-and-previous-elements-out-of-an-array-in-liquid

**Comment by RsCrd** [comment]
Fixed in #378

**Comment by graeme-a-stewart** [comment]
This should have been fixed on merging #378, however we are not seeing links on the website. Needs investigation.

**Comment by graeme-a-stewart** [comment]
Ah, it seems that arbitrary Jekyll plugins are not supported:

https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/

So we need to find a way to work around this.

**Comment by graeme-a-stewart** [comment]
Fixed in #383
