### ISSUE TITLE
Use https for website

### ISSUE THREAD

**Issue by graeme-a-stewart** [HSF/hsf.github.io#351]
The https version of our website does not work, because the certificate is only valid for `*github.io` and `*github.com`.

Github have announced that they now support https for custom domain names:

https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

So we should follow the procedure to enable this for HSF (maybe even disable the http version in time). 

This might need @wenaus to update our DNS entry.

**Comment by wenaus** [comment]
OK updated with 5min TTL. Amazon Route 53 appears not to support ANAME or ALIAS.
Sergey Panitkin @ BNL also has access to the BNL AWS account we're using.

**Comment by graeme-a-stewart** [comment]
Thanks - ok, I will try to republish the site to get the https option working now.

**Comment by graeme-a-stewart** [comment]
It's working perfectly now at https://hepsoftwarefoundation.org/. Thanks for the DNS updates.
