### ISSUE TITLE
Link to nixcon2018.org does not work with https

### ISSUE THREAD

**Issue by JavierCVilla** [HSF/hsf.github.io#561]
The continuous integration is consistenly failing due to this link:

`https://nixcon2018.org/` in this [post](https://github.com/HSF/hsf.github.io/blob/master/organization/_posts/2019/2019-02-27-packaging.md)

The url works without https though.

**Comment by graeme-a-stewart** [comment]
Thanks - I'll fix it. It's very annoying when things like that happen, I had noticed it a while ago, but I usually leave it a little while to see if the website recovers.

**Comment by JavierCVilla** [comment]
@graeme-a-stewart for some links it looks like just retrying the check works, I wonder the plugin offers such a feature.

**Comment by graeme-a-stewart** [comment]
Believe me, if it offered something easy to use that made things more robust, we'd be using it already!
