### ISSUE TITLE
Update calendar handling on website

### ISSUE THREAD

**Issue by graeme-a-stewart** [HSF/hsf.github.io#567]
We have to have far too many manual steps right now for meetings:

- Create Indico.
- Add to community calendar.
- Do a PR to the website for a banner via an “announcement”.

This is tedious, tricky and error prone.

Indico offers (for ages) an export of events from an entire agenda section (e.g., https://indico.cern.ch/export/categ/5816.ics?from=-31d). So I propose that we use this as the “master” source of events. Then try to use a merged view between the classic community calendar and the HSF Indico events.

We should also extract the next 2-3 events for the front page of the website. This would be separare from the classic announcements mechanism, that we will still support.

Might be worth looking at FullCalendar (https://fullcalendar.io/), although that may be too heavy.

**Comment by davidlange6** [comment]
the 'PR to the website' step is certainly something that can be done automatically via GitHub apis. More tricky is to deal properly with events that move around

**Comment by graeme-a-stewart** [comment]
So I was wondering about something a bit more dynamic than that - then the website info gets generated automatically and on the fly from Indico. Even if PRs get generated automatically someone has to look at them and approve them. Plus the problem that the list is only generated at commit time, not at the point the page is loaded.

That also handles meetings that move, disappear, etc.

**Comment by davidlange6** [comment]
well, it doesn't need to be a PR, can be a direct commit.  jekyll doesn't do updates when pages are accessed afaik, if thats what you mean?

but going through all indico events once (eg) per hour and updating the events area is doable I believe (modulo api hit-rate limitations)

**Comment by graeme-a-stewart** [comment]
Duplicate of #726
