### ISSUE TITLE
Simplify School template

### ISSUE THREAD

**Issue by klieret** [HSF/hsf.github.io#651]
Currently the template for adding new training Schools looks like this:

```markdown
---
title:  Alpaka Parallel Programming - Taster Session and Basic Tutorial
source: https://indico.cern.ch/event/858758/
date: 2020-04-27
end_date: 2020-04-27
author: Kilian Lieret
layout: event
categories: Schools
---
[Alpaka Parallel Programming - Taster Session and Basic Tutorial](https://indico.cern.ch/event/858758/)
```

so the body text is always ``[title](source)``.

I think we should automatize this (and not have any body text at all), i.e. only have

```markdown
---
title:  Alpaka Parallel Programming - Taster Session and Basic Tutorial
source: https://indico.cern.ch/event/858758/
date: 2020-04-27
end_date: 2020-04-27
author: Kilian Lieret
layout: event
categories: Schools
---
```
because

1. this avoids copy-paste mistakes
2. this is more future proof, e.g. if we want to change the way the links are displayed consistently (add deadlines etc.)

@GuillermoFidalgo

**Comment by klieret** [comment]
Actually looking at ``list_of_schools.md``, it looks like the body of the template isn't even used anyway, right?  
Or is that used somewhere else?

```markdown
{% assign schools = site.categories.Schools | sort:"date" %}

{% capture now %}{{'now' | date: '%s' | plus: 0 }}{% endcapture %}

## Current and Upcoming Training Schools
#### **Warning** : Application deadlines are **before the date shown**
{% for post in schools %}
  {% capture date %}{{post.end_date | date: '%s' | plus: 0 }}{% endcapture %}
  {% if date > now %}
  1. [**{{post.date | date: "%-d %b"}} - {{post.end_date | date: "%-d %b %Y"}}** - {{post.title}} ]({{post.source}})
  {% endif %}
{% endfor %}

## Past Schools
{% for post in schools reversed %}
  {% capture date %}{{post.end_date | date: '%s' | plus: 0 %}}{% endcapture %}
  {% if date < now %}
  1. [**{{post.date | date: "%-d %b"}} - {{post.end_date | date: "%-d %b %Y"}}** - {{post.title}} ]({{post.source}})
  {% endif %}
{% endfor %}
```

if we just replace

**Comment by GuillermoFidalgo** [comment]
Hi @klieret thanks for opening up this issue.

I agree that this `[text] (url)` in the body of the md files be automated.

When I started adding the schools my first instinct was precisely do what you mention, however I think that the reason for adding the `[text](url)` in the body is because it needs to produce some type of text page just in case

I think @graeme-a-stewart would know more as he suggested to keep this content in the body of the files and gave me this as an example https://raw.githubusercontent.com/HSF/hsf.github.io/master/announcements/_posts/2019-02-04-analysis.md

**Comment by GuillermoFidalgo** [comment]
Also wouldn't it be better if we put all school information in a single .yml file instead of creating possibly hundreds of markdown files? 

We could loop over the yml file and output the same page we have now.

**Comment by klieret** [comment]
Using ``.yml`` seems to be very straightforward: https://jekyllrb.com/docs/datafiles/

It would actually make it slightly easier to add new schools, because one doesn't have to type the date twice, so I agree this would make a lot of sense.

Actually what I thought of was even one step further: To have a tiny python script ``add_training-school.py`` with a simple text based GUI that guides you through it. I would volunteer to do that if you do the jekyll thing (doubt it'd take more than 20-30 minutes to get a script with some basic error checking done).

**Comment by GuillermoFidalgo** [comment]
In that case should we move all existing schools to the new yml file and keep populating or should we just leave as is and only new schools will be read from the yml file?

**Comment by klieret** [comment]
I'd say we migrate all of them to yml in that case.
That should be super easy in just a few lines of python anyway

**Comment by GuillermoFidalgo** [comment]
I will open a new branch and PR for this yml file you can add the python script there.

I'm just copy and pasting them for now but this is what I thought it could look like. 

![image](https://user-images.githubusercontent.com/17858942/73018875-d6042100-3df8-11ea-88ef-86a62d182fe3.png)


(the deadline attribute I think would be best to add them for now so that we don't have to end up manually go line by line checking each one in the future)

**Comment by klieret** [comment]
Looks great!

Just regarding the deadline, shouldn't it also have the same date format as the others, i.e. ``YYYY-MM-DD``?

**Comment by klieret** [comment]
Also I wonder, do we need the ``layout: event`` and ``categories: Schools``? (I think that's a leftover from when we were still using the ``.md``s; anyway it's the same every time and even if we wanted to have some more flexibility eventually, we could just set these two things as default values, right?)

**Comment by GuillermoFidalgo** [comment]
> Looks great!
> 
> Just regarding the deadline, shouldn't it also have the same date format as the others, i.e. `YYYY-MM-DD`?


Sure we could do that




> Also I wonder, do we need the `layout: event` and `categories: Schools`? (I think that's a leftover from when we were still using the `.md`s; anyway it's the same every time and even if we wanted to have some more flexibility eventually, we could just set these two things as default values, right?)

You are correct. For generating the page we want these would be unnecessary

**Comment by klieret** [comment]
So I wrote a simple ``add_event.py`` and will merge my branch with yours if you have it converted to yml.

```python
#!/usr/bin/env python3

import yaml
from datetime import datetime
from pathlib import Path
from collections import namedtuple

Event = namedtuple("Event", ["name", "start_date", "end_date", "deadline", "url"])


def input_event():
    return Event(
        input("Event title "),
        input("Start date [YYYY-MM-DD] "),
        input("End date [YYYY-MM-DD] "),
        input("Deadline [YYYY-MM-DD] "),
        input("Url "),
    )


def check_event(event: Event):
    start_date = datetime.strptime(event.start_date, "%Y-%m-%d")
    end_date = datetime.strptime(event.end_date, "%Y-%m-%d")
    assert end_date >= start_date
    deadline = event.deadline
    if deadline:
        deadline = datetime.strptime(deadline, "%Y-%m-%d")
        assert deadline <= start_date
    assert event.name  
    

class EventDatabase(object):
    def __init__(self, events=None):
        if events is not None:
            self.events = events
        else:
            self.events = []
    
    @classmethod
    def from_file(cls, path: Path):
        with path.open() as stream:
            events = yaml.safe_load(stream)
        return EventDatabase(events)
    
    def write(self, path: Path):
        with path.open("w") as stream:
            yaml.dump(self.events, stream)
        
    def add_event(self, event: Event):
        self.events.append(dict(event._asdict()))


if __name__ == "__main__":
    path = Path(".").parent.parent / "schools.yml"
    if path.is_file():
        edb = EventDatabase.from_file(path)
    else:
        edb = EventDatabase()
    event = input_event()
    check_event(event)
    edb.add_event(event)
    edb.write(path)
```

**Comment by GuillermoFidalgo** [comment]
Sorry it has take so long I have made a PR which add this yml file with all schools I have so far.

**Comment by klieret** [comment]
No worries, thank you for your work. But that PR doesn't seem to include the change required in ``list_of_schools.md`` yet, right?
