### ISSUE TITLE
2019 vs 2020 confusion

### ISSUE THREAD

**Issue by davidlange6** [HSF/hsf.github.io#723]
Hi-
I notice some 2019 vs 2020 errors on the recent HSF meeting minutes as shown on the hsf home page.. I don't think I have time to look in the next week so thought I would report it..

eg
![image](https://user-images.githubusercontent.com/5042883/75049072-d8c26680-54c9-11ea-9061-7ae379c97275.png)

**Comment by graeme-a-stewart** [comment]
Thanks @davidlange6 - I have a pending set of minutes to do, so I will fix this too
