### ISSUE TITLE
How to include additional pages for workinggroups

### ISSUE THREAD

**Issue by klieret** [HSF/hsf.github.io#752]
We want to add additional pages for the training working group. What's the best approach? I could 

# Option 1
change it so that we can have subpages in the workinggroups directory, i.e. 
```sh
cd _workinggroups
mkdir training
mv  training.md training/index.md
touch training/something.md
```
and change the permalink of the workinggroups from ``/workinggroups/:title.html `` to ``/workinggroups/:path.html``  

# Option 2
Have everything training related go to ``hepsoftwarefoundation/trainingdocs/..``, i.e. 
```sh
mkdir trainingdocs
```
and add it to ``_config.yml``. 

# Option 3
Have everything training related (including the training home)  in ``_training`` and set it up so that ``hepsoftwarefoundation.org/training`` goes to the index and ``hepsoftwarefoundation.org/training/something`` goes to the respective pages.
I'd add an additional redirect from ``hepsoftwarefoundation.org/workinggroups/training`` to ``hepsoftwarefoundation.org/training`` to not break any links.

**Comment by klieret** [comment]
I personally favor the option 3 because of the short and concise URL.

**Comment by graeme-a-stewart** [comment]
Hi @klieret - I think Option 3 sounds generally good. However, I think that a landing page for the Training WG needs to be maintained in `_workinggroups/training.md` as the set of pages here are use dynamically in a few places:

https://github.com/HSF/hsf.github.io/blob/3acabc613a47db88b22093d948602e12d494c37c/_includes/navbar.ext#L29

So if it was being redirected it would get lost.

**Comment by klieret** [comment]
Thanks! Let's review the details on #757
