### ISSUE TITLE
web problems for education page

### ISSUE THREAD

**Issue by danielskatz** [HSF/hsf.github.io#780]
The linkedin link for Jim Pivarski on https://hepsoftwarefoundation.org/training/community isn't being generated correctly.

I assume something is wrong in https://github.com/HSF/hsf.github.io/blob/master/_educators/jim_pivarski.md
The only think I see is the "null" that perhaps should just be blank.

@klieret ?

**Comment by klieret** [comment]
Thanks for checking that! Indeed, I just fixed that.
