### ISSUE TITLE
Floating heads for WGs

### ISSUE THREAD

**Issue by graeme-a-stewart** [HSF/hsf.github.io#835]
We agreed at the HSF coordination meeting that it would be good to implement the floating heads for the convenors of all the WGs, generalising what was done for the training group.

@klieret as the person who did the nice training implementaion can you see how to implement this easily?

**Comment by klieret** [comment]
Hi @graeme-a-stewart . Yes, I think this isn't too hard. Currently I'm very busy with organizing a starterkit workshop for Belle2, but I will definitely find the time for it by mid October (I'm planning to work on this sooner, but just can't promise anything...).

**Comment by graeme-a-stewart** [comment]
Thanks a lot @klieret - October would of course be just fine!
