### ISSUE TITLE
Typography/Design improvements

### ISSUE THREAD

**Issue by klieret** [HSF/hsf.github.io#847]
For being a text-heavy page (which we undoubtedly are), our base font size of 16px is unusually small. Most web design pages recommend 18px (or even larger) for such low-interaction websites.

Sources

* [learnui.design](https://learnui.design/blog/mobile-desktop-website-font-size-guidelines.html)
* [w3-lab.com](https://w3-lab.com/web-design/how-big-should-a-font-be-on-a-site-rules-of-typography/)

I think this would also *look* much better on this kind of bleak, media deplete layout that most of our sub-pages have. Medium.com for example has even 21px!

**Comment by klieret** [comment]
I'd also suggest slightly increased page margin.

And perhaps there's more suggestions to make the design a bit friendlier?

**Comment by NinaPacifier** [comment]
@klieret I am new to open source contribution. May I work on its issue???

**Comment by klieret** [comment]
Hi @NinaPacifier  sure, I haven't started working on this. Design changes are a bit of a "political" topic though, you need to convince people that the results looks better ;)

**Comment by NinaPacifier** [comment]
@klieret  I will try my best :)

**Comment by vinayakd1729** [comment]
I see the font size of main text is 14px through inspect element. 16px seems good with relative to other headings and other elements. I have build some blogs on GitHub pages earlier and I have experience. May I work on this issue?

**Comment by hegner** [comment]
@vinayakd1729 - seems this ticket went a bit dormant. Feel free to prepare a merge request with your ideas. We can take it from there then.

**Comment by nimishbongale** [comment]
Can I take this up @hegner @klieret?

If I get the issue correctly, we are looking to increase the font size by a few px's?

**Comment by klieret** [comment]
Nobody has submitted a pull request for this so far, so I'm sure it's fine :)   Should be pretty trivial code wise and more a question of good design :)

**Comment by klieret** [comment]
@nimishbongale  I'm pretty much an amateur in this area ;)  Probably best to just play around with different things to tweak, create a couple of screenshots and see what people like :)

**Comment by klieret** [comment]
another idea: https://github.com/HSF/hsf.github.io/pull/965

**Comment by nimishbongale** [comment]
Have been having some issues with my health lately, I'm sorry for not following up. I'll be sure to give in my insights though!

**Comment by klieret** [comment]
Health goes first! No pressure at all, hope you recover soon!

**Comment by klieret** [comment]
I think we now completed every change that we had discussed, so I will close this.
