### ISSUE TITLE
Link checker issue tracking

### ISSUE THREAD

**Issue by graeme-a-stewart** [HSF/hsf.github.io#883]
Just to note we had a glitch on the last merge into the master branch <https://github.com/HSF/hsf.github.io/runs/1783028603?check_suite_focus=true>

```
Using markdown-link-check configuration file: .github/config/mdcheck.json
USE_QUIET_MODE: no
USE_VERBOSE_MODE: yes
FOLDER_PATH: .
MAX_DEPTH: -1
CHECK_MODIFIED_FILES: yes
FILE_EXTENSION: .md
FILE_PATH: 
BASE_BRANCH: master
remote: Not Found
fatal: repository 'https://github.com/HSF/hsf.github.io/' not found
```

Not a great start, sadly!

**Comment by graeme-a-stewart** [comment]
Just to note that the next test on push succeeded!

**Comment by graeme-a-stewart** [comment]
https://github.com/HSF/hsf.github.io/pull/891 shows a false positive failure as the link checker doesn't seem to like `mailto:` links where multiple email addresses are given, separated by commas. It may well be that we're not using the correct syntax for multiple emails, although it in practive the CSV addresses work fine for me.

**Comment by graeme-a-stewart** [comment]
OK, AFAICS from the relevant RFC comma separated values are legal:

```
to           = addr-spec *("," addr-spec )
```

https://tools.ietf.org/html/rfc6068

So I guess this is a flaw in the link checker itself

**Comment by Ayushsunny** [comment]
Is this issue still persist @graeme-a-stewart ?

**Comment by graeme-a-stewart** [comment]
Hello @Ayushsunny - the false positive on multiple email addresses does still exist, though it's a very easy one to work around. It would be rather useful to raise an issue and propose a fix in the underlyng tool.

**Comment by Ayushsunny** [comment]
> Hello @Ayushsunny - the false positive on multiple email addresses does still exist, though it's a very easy one to work around. It would be rather useful to raise an issue and propose a fix in the underlying tool.

sorry, I didn't get you sir

**Comment by graeme-a-stewart** [comment]
Hi @Ayushsunny

I mean the issue identified here is not for this repository, rather it's a problem in https://github.com/tcort/markdown-link-check (or probaly even underlying that in https://www.npmjs.com/package/isemail https://github.com/skeggse/isemail) that multiple recipients for a `mailto:` are not recognised.

That's where it should be fixed.

For us we just apply a workaround here https://github.com/gaurav-nelson/github-action-markdown-link-check#disable-check-for-some-links to prevent the few places where this is used from causing a false positive.

Graeme

**Comment by Ayushsunny** [comment]
> Hi @Ayushsunny
> 
> I mean the issue identified here is not for this repository, rather it's a problem in https://github.com/tcort/markdown-link-check (or probaly even underlying that in https://www.npmjs.com/package/isemail https://github.com/skeggse/isemail) that multiple recipients for a `mailto:` are not recognised.
> 
> That's where it should be fixed.
> 
> For us we just apply a workaround here https://github.com/gaurav-nelson/github-action-markdown-link-check#disable-check-for-some-links to prevent the few places where this is used from causing a false positive.
> 
> Graeme

Okay thank you so much for explaining this nicely sir @graeme-a-stewart 
Actually sir I'm new to open source and I want a nice mentor like you to work under and learn something good

**Comment by hegner** [comment]
@graeme-a-stewart - is it OK to close?

**Comment by graeme-a-stewart** [comment]
Yes, I think we can now - the new link checker is working very well at the moment
